
# Promtail configuration
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchwait: 1s
    batchsize: 1048576

scrape_configs:
  - job_name: localstack
    static_configs:
      - targets:
          - localhost
        labels:
          job: localstack
          __path__: /var/log/localstack/*.log
