version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest           # asegúrate de usar ≥ v2.3
    container_name: localstack
    ports:
      - "4566:4566"   # Edge (todos los servicios)
      - "4510-4559:4510-4559"   # puertos internos (recomendado)
    environment:
      - SERVICES=sns,sqs,lambda,cloudformation,iam,sts,logs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LOCALSTACK_TMP_FOLDER=/tmp/localstack_tmp
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=${LOCALSTACK_AUTH_TOKEN}  # <-- añade tu API key aquí
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./localstack_tmp:/tmp/localstack_tmp
    command: >
      sh -c "localstack start --host"

networks:
  default:
    name: lsnet

#version: "3.8"
#
#services:
#  localstack:
#    image: localstack/localstack
#    container_name: localstack
#    ports:
#      - "4566:4566"
#    environment:
#      - SERVICES=s3,dynamodb,lambda
#      - DEBUG=1
#      - DATA_DIR=/tmp/localstack/data
#      - LOCALSTACK_TMP_FOLDER=/tmp/localstack_tmp  # Cambio para usar otro tmp
#      - DOCKER_HOST=unix:///var/run/docker.sock
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
#      - ./localstack_tmp:/tmp/localstack_tmp  # Volumen apuntando al nuevo tmp
